#!/usr/bin/env node
/**
 * bienzoli Google Drive — Init Script
 *
 * Creates the /bienzoli/ folder structure in Google Drive.
 * Saves all folder IDs to scripts/gdrive-folders.json.
 * Updates GDRIVE_ROOT_FOLDER_ID in .env.local.
 *
 * Agent: AGENT 09 — CLOUD ARCHIVIST
 *
 * Usage:
 *   node --env-file=.env.local scripts/gdrive-init.mjs
 *   npm run gdrive:init
 */

import { google } from 'googleapis'
import { readFileSync, writeFileSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')

// ─── Auth ──────────────────────────────────────────────────────────────────

const {
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_REDIRECT_URI,
  GOOGLE_REFRESH_TOKEN,
} = process.env

if (!GOOGLE_CLIENT_ID || !GOOGLE_CLIENT_SECRET || !GOOGLE_REFRESH_TOKEN) {
  console.error('Missing required env vars: GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, GOOGLE_REFRESH_TOKEN')
  console.error('Run with: node --env-file=.env.local scripts/gdrive-init.mjs')
  process.exit(1)
}

const auth = new google.auth.OAuth2(
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_REDIRECT_URI || 'http://localhost:3000/api/auth/google/callback',
)
auth.setCredentials({ refresh_token: GOOGLE_REFRESH_TOKEN })

const drive = google.drive({ version: 'v3', auth })

// ─── Helpers ───────────────────────────────────────────────────────────────

/**
 * Find an existing folder by name within a parent (or in root).
 * Returns the folder ID if found, null otherwise.
 */
async function findFolder(name, parentId = null) {
  const q = parentId
    ? `name = '${name}' and mimeType = 'application/vnd.google-apps.folder' and '${parentId}' in parents and trashed = false`
    : `name = '${name}' and mimeType = 'application/vnd.google-apps.folder' and 'root' in parents and trashed = false`

  const res = await drive.files.list({
    q,
    fields: 'files(id, name)',
    spaces: 'drive',
  })

  return res.data.files?.length > 0 ? res.data.files[0].id : null
}

/**
 * Create a folder. Returns the new folder ID.
 */
async function createFolder(name, parentId = null) {
  const metadata = {
    name,
    mimeType: 'application/vnd.google-apps.folder',
    ...(parentId ? { parents: [parentId] } : {}),
  }

  const res = await drive.files.create({
    requestBody: metadata,
    fields: 'id',
  })

  return res.data.id
}

/**
 * Find or create a folder. Returns { id, created }.
 */
async function ensureFolder(name, parentId = null) {
  const existing = await findFolder(name, parentId)
  if (existing) {
    return { id: existing, created: false }
  }
  const id = await createFolder(name, parentId)
  return { id, created: true }
}

// ─── Main ──────────────────────────────────────────────────────────────────

const SUBFOLDER_NAMES = [
  'docs',
  'case-studies',
  'social-cards',
  'client-deliverables',
  'videos',
  'invoices',
  'contracts',
  'content',
]

async function init() {
  console.log('\nbienzoli Google Drive Init')
  console.log('══════════════════════════\n')

  // 1. Ensure root /bienzoli/ folder
  console.log('Checking root folder /bienzoli/...')
  const root = await ensureFolder('bienzoli')
  console.log(`  ${root.created ? '✓ Created' : '→ Found'} /bienzoli/ — ID: ${root.id}\n`)

  // 2. Ensure all sub-folders
  const folderIds = { root: root.id }

  for (const name of SUBFOLDER_NAMES) {
    process.stdout.write(`  Checking /bienzoli/${name}/...`)
    const folder = await ensureFolder(name, root.id)
    folderIds[name] = folder.id
    console.log(` ${folder.created ? '✓ Created' : '→ Found'} — ID: ${folder.id}`)
  }

  // 3. Write scripts/gdrive-folders.json
  const foldersPath = join(ROOT, 'scripts', 'gdrive-folders.json')
  const foldersData = {
    _comment: 'Google Drive folder IDs for bienzoli sync. Auto-generated by gdrive-init.mjs',
    ...folderIds,
  }
  writeFileSync(foldersPath, JSON.stringify(foldersData, null, 2) + '\n')
  console.log('\n✓ Wrote scripts/gdrive-folders.json')

  // 4. Update GDRIVE_ROOT_FOLDER_ID in .env.local
  const envPath = join(ROOT, '.env.local')
  let envContent = readFileSync(envPath, 'utf8')

  if (envContent.includes('GDRIVE_ROOT_FOLDER_ID=')) {
    // Replace existing (possibly empty) value
    envContent = envContent.replace(
      /^GDRIVE_ROOT_FOLDER_ID=.*$/m,
      `GDRIVE_ROOT_FOLDER_ID=${root.id}`,
    )
  } else {
    // Append
    envContent += `\nGDRIVE_ROOT_FOLDER_ID=${root.id}\n`
  }

  writeFileSync(envPath, envContent)
  console.log('✓ Updated GDRIVE_ROOT_FOLDER_ID in .env.local')

  // 5. Summary
  console.log('\n══════════════════════════')
  console.log('Init complete.\n')
  console.log('Folder map:')
  for (const [key, id] of Object.entries(folderIds)) {
    const path = key === 'root' ? '/bienzoli/' : `/bienzoli/${key}/`
    console.log(`  ${path.padEnd(30)} ${id}`)
  }
  console.log('\nNext step: npm run gdrive:sync')
}

init().catch((err) => {
  console.error('\nInit failed:', err.message)
  if (err.errors) {
    for (const e of err.errors) console.error(' -', e.message)
  }
  process.exit(1)
})
